# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'draw_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
import random, time

from PyQt5.QtCore import QTimer, QThread
from PyQt5.QtWidgets import QMessageBox, QWidget

PEOPLE_LIST = []
PEOPLE_NUM = 1
RANDOM_NUM_LIST = []


class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 801, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(36)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 160, 801, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_num = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_num.sizePolicy().hasHeightForWidth())
        self.label_num.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华光方珊瑚_CNKI")
        font.setPointSize(72)
        self.label_num.setFont(font)
        self.label_num.setStyleSheet("color : rgb(255, 0, 0)")
        self.label_num.setText("")
        self.label_num.setAlignment(QtCore.Qt.AlignCenter)
        self.label_num.setObjectName("label_num")
        self.verticalLayout_2.addWidget(self.label_num)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(151, 480, 220, 61))
        self.pushButton.clicked.connect(self.start)

        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(420, 480, 220, 61))
        self.pushButton1.clicked.connect(self.end)
        self.pushButton1.setDisabled(True)

        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton")
        self.lineEdit_pertime = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pertime.setGeometry(QtCore.QRect(408, 419, 86, 31))
        self.lineEdit_pertime.setObjectName("lineEdit_pertime")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 419, 80, 27))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_people = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_people.setGeometry(QtCore.QRect(408, 370, 86, 31))
        self.lineEdit_people.setObjectName("lineEdit_people")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(321, 370, 80, 27))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 131, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.timer = QTimer()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "抽奖"))
        self.label_title.setText(_translate("MainWindow", "双旦嘉年华"))
        self.pushButton.setText(_translate("MainWindow", "开始抽奖"))
        self.pushButton1.setText(_translate("MainWindow", "停止抽奖"))
        self.lineEdit_pertime.setText(_translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "抽几人："))
        self.lineEdit_people.setText(_translate("MainWindow", "60"))
        self.label.setText(_translate("MainWindow", "总人数："))

    def start(self):
        global PEOPLE_LIST
        global PEOPLE_NUM

        people_num = int(self.lineEdit_people.text())
        people_draw_num = int(self.lineEdit_pertime.text())

        if people_num != PEOPLE_NUM:
            PEOPLE_NUM = people_num
            PEOPLE_LIST = list(range(1, people_num + 1))
        self.timer.timeout.connect(self.add)
        self.timer.start(60)
        self.pushButton.setDisabled(True)
        self.pushButton1.setDisabled(False)
        self.lineEdit_people.setDisabled(True)
        self.lineEdit_pertime.setDisabled(True)

    def end(self):
        global RANDOM_NUM_LIST
        global PEOPLE_LIST
        self.timer.stop()
        people_num = int(self.lineEdit_people.text())

        for num in RANDOM_NUM_LIST:
            PEOPLE_LIST.remove(int(num))

        if len(PEOPLE_LIST) == 0:
            reply = QMessageBox.question(self, '已抽完所有人', '所有人已被抽过，是否重新开始？',
                                         QMessageBox.Yes , QMessageBox.Yes)
            if reply == QMessageBox.Yes:
                PEOPLE_LIST = list(range(1, people_num + 1))

        self.pushButton.setDisabled(False)
        self.pushButton1.setDisabled(True)
        self.lineEdit_people.setDisabled(False)
        self.lineEdit_pertime.setDisabled(False)

    def add(self):
        global RANDOM_NUM_LIST
        global PEOPLE_LIST

        people_draw_num = int(self.lineEdit_pertime.text())
        people_num = int(self.lineEdit_people.text())
        if people_draw_num <= len(PEOPLE_LIST):
            RANDOM_NUM_LIST = [str(num) for num in random.sample(PEOPLE_LIST, people_draw_num)]
            # print(random_num_list)
            random_result = ' '.join(RANDOM_NUM_LIST)
            # print(random_result)
            self.label_num.setText(random_result)
        else:
            reply = QMessageBox.question(self, '已抽完所有人', '所有人已被抽过，是否重新开始？',
                                         QMessageBox.Yes, QMessageBox.Yes)
            if reply == QMessageBox.Yes:
                PEOPLE_LIST = list(range(1, people_num + 1))

